version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: gear-case-finder-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=gear-case-finder

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gear-case-finder-app
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/gear-case-finder
    restart: always

volumes:
  mongodb_data:
